export const eventListDummy = [
    {
        eventName: 'Test Tournument',
        id: '2',
        date: '20 20 2020',
        athletesList: [
            {
                id: '1',
                firstName: 'Evgeny',
                lastName: 'Poboykin',
                gender_label: 'МУЖЧИНА',
                gender_value: 'MALE',
                bornYear: 1985,
                selfWeight: 92,
                country: '',
                city: '',
                coach: '',
                team: '',
                sq_weight_1: 100,
                sq_weight_2: 0,
                sq_weight_3: 0,
                sq_weight_4: 0,
                sq_weight_5: 0,
                bp_weight_1: 100,
                bp_weight_2: 0,
                bp_weight_3: 0,
                bp_weight_4: 0,
                bp_weight_5: 0,
                dl_weight_1: 100,
                dl_weight_2: 0,
                dl_weight_3: 0,
                dl_weight_4: 0,
                dl_weight_5: 0,
                personal_result_sq: 0,
                personal_result_bp: 0,
                personal_result_dl: 0,
                abs_weight: 0,
                abs_result: 0,
            },
            {
                id: '2',
                firstName: 'Buum',
                lastName: 'Chololaca',
                gender_label: 'ЖЕНЩИНА',
                gender_value: 'FEMALE',
                bornYear: 1995,
                selfWeight: 82,
                country: '',
                city: '',
                coach: '',
                team: '',
                sq_weight_1: 100,
                sq_weight_2: 13,
                sq_weight_3: 0,
                sq_weight_4: 0,
                sq_weight_5: 0,
                bp_weight_1: 100,
                bp_weight_2: 0,
                bp_weight_3: 0,
                bp_weight_4: 0,
                bp_weight_5: 0,
                dl_weight_1: 100,
                dl_weight_2: 0,
                dl_weight_3: 0,
                dl_weight_4: 0,
                dl_weight_5: 0,
                personal_result_sq: 0,
                personal_result_bp: 0,
                personal_result_dl: 0,
                abs_weight: 0,
                abs_result: 0,
            },
        ],
        label: 'IPF (Classic)',
        value: 'IPF-Classic',
        four: true,
        five: true,
        setFourBtnActive: false,
        setFiveBtnActive: false,
        disFourBtn: false,
        disFiveBtn: true,
        disDelBtn: true,
        sq: false,
        bp: false,
        dl: false,
        pss: true,
        gsl: true,
        ts: true,
        title: false,
        card: 0,
    },
];
