import { IAthlete } from './interfaces';

export const Athlete: IAthlete = {
    id: '',
    firstName: '',
    lastName: '',
    gender_label: 'МУЖЧИНА',
    gender_value: 'MALE',
    bornYear: 1990,
    selfWeight: 0,
    country: '',
    city: '',
    coach: '',
    team: '',
    sq_weight_1: 0,
    sq_weight_2: 0,
    sq_weight_3: 0,
    sq_weight_4: 0,
    sq_weight_5: 0,
    bp_weight_1: 0,
    bp_weight_2: 0,
    bp_weight_3: 0,
    bp_weight_4: 0,
    bp_weight_5: 0,
    dl_weight_1: 0,
    dl_weight_2: 0,
    dl_weight_3: 0,
    dl_weight_4: 0,
    dl_weight_5: 0,
    personal_result_sq: 0,
    personal_result_bp: 0,
    personal_result_dl: 0,
    abs_weight: 0,
    abs_result: 0,
};
