import { IEventTemplate } from './interfaces';

export const EventTemplate: IEventTemplate = {
    eventName: '',
    id: '',
    date: null,
    athletesList: [],
    label: 'IPF (Classic)',
    value: 'IPF-Classic',
    four: true,
    five: true,
    setFourBtnActive: false,
    setFiveBtnActive: false,
    disFourBtn: false,
    disFiveBtn: true,
    disDelBtn: true,
    sq: false,
    bp: false,
    dl: false,
    pss: true,
    gsl: true,
    ts: true,
    title: false,
    card: 0,
};
