export const Language_RU = {
    event_name: 'Название Мероприятия',
    create_event: 'Создать Мероприятие',
    add_spostsman: 'Добавить Спортсмена',
    save_as: 'Сохранить Как',
    delete_btn: 'УДАЛИТЬ',
    standart: 'СТАНДАРТНО',
    pro: 'ПРО',
    form: {
        cansel: 'отмена',
        save_as: 'СОХРАНИТЬ ИЗМЕНЕНИЯ',
        save: 'ДОБАВИТЬ УЧАСТНИКА',
        first_name: 'ИМЯ',
        last_name: 'ФАМИЛИЯ',
        country: 'СТРАНА',
        city: 'ГОРОД',
        coach: 'ТРЕНЕР',
        team: 'КОМАНДА',
        gender_male: 'МУЖЧИНА',
        gender_female: 'ЖЕНЩИНА',
    },
};
export const Language_EN = {
    event_name: 'Event Name',
    create_event: 'Create Event',
    add_spostsman: 'Add Sportsman',
    save_as: 'Save As',
    delete_btn: 'DELETE',
    standart: 'STANDART',
    pro: 'PRO',
    form: {
        cansel: 'cansel',
        save_as: 'Save',
        save: 'ADD SPORTSMAN',
        first_name: 'FIRST NAME',
        last_name: 'LAST NAME',
        country: 'COUNTRY',
        city: 'CITY',
        coach: 'COACH',
        team: 'TEAM',
        gender_male: 'MALE',
        gender_female: 'FEMALE',
    },
};
