import { ILanguage } from './interfaces';

export const Language_RU: ILanguage = {
    event_name: 'Название Мероприятия',
    create_event: 'Создать Мероприятие',
    add_athlete: 'Добавить Спортсмена',
    save_as: 'Сохранить Как',
    delete_btn: 'УДАЛИТЬ',
    standard: 'СТАНДАРТНО',
    pro: 'ПРО',
    list: 'список спортсменов',
    result: 'результат',
    form: {
        cancel: 'отмена',
        save_changes: 'СОХРАНИТЬ ИЗМЕНЕНИЯ',
        save_add: 'ДОБАВИТЬ УЧАСТНИКА',
        first_name: 'ИМЯ',
        last_name: 'ФАМИЛИЯ',
        country: 'СТРАНА',
        city: 'ГОРОД',
        coach: 'ТРЕНЕР',
        team: 'КОМАНДА',
        gender_male: 'МУЖЧИНА',
        gender_female: 'ЖЕНЩИНА',
        squat: 'ПРИСЕДАНИЯ СО ШТАНГОЙ',
        bench_press: 'ЖИМ ШТАНГИ ЛЕЖА',
        dead_lift: 'ТЯГА ШТАНГИ',
    },
};
export const Language_EN: ILanguage = {
    event_name: 'Event Name',
    create_event: 'Create Event',
    add_athlete: 'Add Sportsman',
    save_as: 'Save As',
    delete_btn: 'DELETE',
    standard: 'STANDART',
    pro: 'PRO',
    list: 'sportsmans data',
    result: 'result',
    form: {
        cancel: 'cancel',
        save_changes: 'Save',
        save_add: 'ADD SPORTSMAN',
        first_name: 'FIRST NAME',
        last_name: 'LAST NAME',
        country: 'COUNTRY',
        city: 'CITY',
        coach: 'COACH',
        team: 'TEAM',
        gender_male: 'MALE',
        gender_female: 'FEMALE',
        squat: 'SQUAT',
        bench_press: 'BENCH PRESS',
        dead_lift: 'DEADLIFT',
    },
};
